GET http://localhost:5000/user/show HTTP/1.1


### 
POST http://localhost:5000/user/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Emmytobs",
    "email": "emmytobs@gmail.com",
    "password": "Emmytobs"
}


###
POST http://localhost:5000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "Emmytobs",
    "password": "Emmytobs"
}

###
GET http://localhost:5000/user/profile HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWQ4MzQ1MzFiODQzYTA5NDBlMGFkNzAiLCJpYXQiOjE1OTEyMzE2Nzd9.wgPUgal-7VrFMNXYErHxOyVyXTlsJU5Jdmn90Kn0O7U